models/Applications.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "applications".
 *
 * @property int $id
 * @property string $status Статус
 * @property string $customer_id Клиент
 * @property int $full_name_id ФИО
 * @property string $phone Телефон
 * @property string $request Заявка
 * @property string $date_of_adoption Дата принятия
 * @property string $date_of_completion Дата выполнения
 * @property string $date_of_payment Дата оплаты
 * @property int $accepted_id Принял
 * @property int $fulfilled_id Выполнил
 * @property string $comment Комментарий
 * @property string $sum Сумма
 * @property string $payment Расчет
 * @property string $telephone Телефон
 * @property string $material_price Цена материала
 * @property string $price_of_work Цена работы
 */
class Applications extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'applications';
    }
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => null,
                'createdAtAttribute' => 'date_of_adoption',
                'value' => date('Y-m-d H:i:s'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['accepted_id', 'fulfilled_id' ,'customer_id'], 'integer'],
            ['full_name_id', 'validateClient'],
            [['full_name_id'],'required', 'when' => function ($model) {
             return $model->customer_id == 1;
            }],
            [['date_of_adoption', 'date_of_completion', 'date_of_payment','full_name_id' ], 'safe'],
            [['status', 'phone', 'request', 'comment', 'sum', 'payment', 'telephone', 'material_price', 'price_of_work'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Статус',
            'customer_id' => 'Клиент',
            'full_name_id' => 'ФИО',
            'phone' => 'Телефон',
            'request' => 'Заявка',
            'date_of_adoption' => 'Дата принятия',
            'date_of_completion' => 'Дата выполнения',
            'date_of_payment' => 'Дата оплаты',
            'accepted_id' => 'Принял',
            'fulfilled_id' => 'Выполнил',
            'comment' => 'Комментарий',
            'sum' => 'Сумма',
            'payment' => 'Расчет',
            'telephone' => 'Телефон',
            'material_price' => 'Цена материала',
            'price_of_work' => 'Цена работы',
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(Customer::className(), ['id' => 'customer_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFull_name()
    {
        return $this->hasOne(FullName::className(), ['id' => 'full_name_id']);
    }

    public function validateClient($attribute, $params)
    {
        $client = FullName::find()->where(['id' => $this->full_name_id])->one();
        if (!isset($client))
        {
            $client = new FullName();
            $client->name = $this->full_name_id;
            $error = $client->errors;

            if ($client->save())
            {
                $this->full_name_id = $client->id;
            }
            else
            {
                $this->addError($attribute,"Не создан новый клиент");
            }
        }
    }

    /**
     * @inheritdoc
     * @return ApplicationsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ApplicationsQuery(get_called_class());
    }
}

controllers/ApplicationsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Applications;
use app\models\ApplicationsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * ApplicationsController implements the CRUD actions for Applications model.
 */
class ApplicationsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Applications models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new ApplicationsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Applications model.
     * 
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "заявка #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Изменить',['update', 'id' => $model->id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new Applications model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Applications();  

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить заявку",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Добавить заявку",
                    'content'=>'<span class="text-success">Создание заявок успешно завершено</span>',
                    'footer'=> Html::button('ОК',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Создать еще',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])
        
                ];         
            }else{           
                return [
                    'title'=> "Добавить заявку",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    /**
     * Updates an existing Applications model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * 
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить заявку #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'forceClose' => true,
                ];    
            }else{
                 return [
                    'title'=> "Изменить заявку #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing Applications model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * 
     * @return mixed
     */
    public function actionDelete($id, $containerPjaxReload = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>$containerPjaxReload];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }
    public function actionToWork($id, $containerPjaxReload = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $model->status = 'В работе';
        $model->save();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>$containerPjaxReload];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }
    public function actionToPay($id, $containerPjaxReload = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $model->status = 'Ожидает оплаты';
        $model->save();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>$containerPjaxReload];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }
    public function actionToSuccess($id, $containerPjaxReload = '#crud-datatable-pjax')
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $model->status = 'Готово';
        $model->date_of_completion = date('Y-m-d H:i:s');
        $model->date_of_payment = date('Y-m-d H:i:s');
        $model->fulfilled_id = Yii::$app->user->identity->id;
        $model->save();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>$containerPjaxReload];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

     /**
     * Delete multiple existing Applications model.
     * For ajax request will return json object

views/applications/_columns.php
<?php

use app\models\Customer;
use app\models\FullName;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use kartik\grid\GridView;

return [

    [
        'class' => 'kartik\grid\DataColumn',
        'attribute'=>'id',
        'filter' => false
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'status',
        'filter' => [
            'Принят' => 'Принят',
            'В работе' => 'В работе',
            'Ожидает оплаты' => 'Ожидает оплаты',
            'Готово' => 'Готово',
        ],
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'customer_id',
        'content' => function($data){
            $customer = ArrayHelper::getColumn(Customer::find()->where(['id' => $data->customer_id])->all(), 'name');
            return implode('',$customer);

        },
        'filter' => false

    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'full_name_id',
        'content' => function($data){
            $customer = ArrayHelper::getColumn(FullName::find()->where(['id' => $data->full_name_id])->all(), 'name');
            return implode('',$customer);

        },
        'filter' => false

    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'request',
        'filter' => false
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'date_of_adoption',
        'filter' => false
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'date_of_completion',
        'value'     => function ($model) {
            if ($model->date_of_completion != null) {
                return $model->date_of_completion;
            } else {
                return '';
            }
        },
        'filter' => false
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'date_of_payment',
        'value'     => function ($model) {
            if ($model->date_of_payment != null) {
                return $model->date_of_payment;
            } else {
                return '';
            }
        },
        'filter' => false
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'accepted_id',
        'content' => function($data){
            $customer = ArrayHelper::getColumn(\app\models\User::find()->where(['id' => $data->accepted_id])->all(), 'name');
            return implode('',$customer);

        },
        'filter' => false

    ],

    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'fulfilled_id',
        'content' => function($data){
            $customer = ArrayHelper::getColumn(\app\models\User::find()->where(['id' => $data->fulfilled_id])->all(), 'name');
            return implode('',$customer);

        },
        'filter' => false
    ],

    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'comment',
        'filter' => false
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'sum',
        'filter' => false
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'payment',
        'filter' => false
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'label' => 'Действия',
        'content' => function($model){
            $update = Html::a('<i class="fa fa-pencil" style="font-size: 16px;"></i>', ['applications/update', 'id' => $model->id],
                ['role'=>'modal-remote','title'=>'Изменить', 'data-toggle'=>'tooltip']
            );
            $delete = Html::a('<i class="fa fa-trash text-danger" style="font-size: 16px;"></i>', ['applications/delete', 'id' => $model->id, 'containerPjaxReload' => '#pjax-container-info-container'],[
                'role'=>'modal-remote','title'=>'Удалить',
                'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                'data-request-method'=>'post',
                'data-toggle'=>'tooltip',
                'data-confirm-title'=>'Вы уверены?',
                'data-confirm-message'=>'Вы действительно хотите удалить файл',
                'style' => 'margin-left: 10px;',
            ]);
           if ($model->status == 'Принят'){
              $toWork =  Html::a('<i class="fa fa-cogs text-success" style="font-size: 16px;"></i>', ['applications/to-work', 'id' => $model->id, 'containerPjaxReload' => '#pjax-container-info-container'],[
                  'role'=>'modal-remote','title'=>'в работу',
                  'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                  'data-request-method'=>'post',
                  'data-toggle'=>'tooltip',
                  'data-confirm-title'=>'Вы уверены?',
                  'data-confirm-message'=>'Вы действительно хотите перевести заявку в работу',
                  'style' => 'margin-left: 10px;',
              ]);
              return $update . $toWork . $delete;

           }elseif ($model->status == 'В работе'){
               $toPay =  Html::a('<i class="fa fa-usd text-success" style="font-size: 16px;"></i>', ['applications/to-pay', 'id' => $model->id, 'containerPjaxReload' => '#pjax-container-info-container'],[
                   'role'=>'modal-remote','title'=>'в оплату',
                   'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                   'data-request-method'=>'post',
                   'data-toggle'=>'tooltip',
                   'data-confirm-title'=>'Вы уверены?',
                   'data-confirm-message'=>'Вы действительно хотите перевести заявку в статус ожидает оплаты?',
                   'style' => 'margin-left: 10px;',
               ]);
               return $update . $toPay . $delete;

           }elseif ($model->status == 'Ожидает оплаты'){
               $toSuccess =  Html::a('<i class="fa fa-check-square-o text-success" style="font-size: 16px;"></i>', ['applications/to-success', 'id' => $model->id, 'containerPjaxReload' => '#pjax-container-info-container'],[
                   'role'=>'modal-remote','title'=>'готово',
                   'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                   'data-request-method'=>'post',
                   'data-toggle'=>'tooltip',
                   'data-confirm-title'=>'Вы уверены?',
                   'data-confirm-message'=>'Вы действительно хотите перевести заявку в готово?',
                   'style' => 'margin-left: 10px;',
               ]);
               return $update . $toSuccess . $delete;
           }else{
               return $update . $delete;
           }
        }
    ],

//    [
//        'class' => 'kartik\grid\ActionColumn',
//        'dropdown' => false,
//        'vAlign'=>'middle',
//        'urlCreator' => function($action, $model, $key, $index) {
//                return Url::to([$action,'id'=>$key]);
//        },
//        'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
//        'updateOptions'=>['role'=>'modal-remote','title'=>'Update', 'data-toggle'=>'tooltip'],
//        'deleteOptions'=>['role'=>'modal-remote','title'=>'Delete',
//                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
//                          'data-request-method'=>'post',
//                          'data-toggle'=>'tooltip',
//                          'data-confirm-title'=>'Are you sure?',
//                          'data-confirm-message'=>'Are you sure want to delete this item'],
//    ],

];   

views/applications/_form.php
<?php

use kartik\datetime\DateTimePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
$matPrice = <<<JS
        let matVal = $(this).val();
        let workVal = document.getElementById("applications-price_of_work").value;
        let sum = Number(matVal) + Number(workVal);
        document.getElementById("applications-sum").value = sum;
        
JS;
$workPrice = <<<JS
        let workVal= $(this).val();
        let matVal = document.getElementById("applications-material_price").value;
        let sum = Number(matVal) + Number(workVal);
        document.getElementById("applications-sum").value = sum;
     
JS;
?>

<div class="applications-form">

    <?php $form = ActiveForm::begin(); ?>


        <div class="row">
            <div class="col-md-6">
                    <?= $form->field($model, 'status')->dropDownList([
                            'Принят' => 'Принят',
                            'В работе' => 'В работе',
                            'Ожидает оплаты' => 'Ожидает оплаты',
                            'Готово' => 'Готово',
                    ])?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'customer_id')->widget(Select2::class, [
                    'data' => ArrayHelper::map(\app\models\Customer::find()->all(), 'id', 'name'),
                    'options' => [
                        'placeholder' => 'Выберите'
                    ],
                ]) ?>
            </div>
        </div>

    

        <div class="row">
            <div class="col-md-6">

                    <?= $form->field($model, 'full_name_id')->widget(kartik\select2\Select2::classname(), [
                        'data' => ArrayHelper::map(\app\models\FullName::find()->all(), 'id', 'name'),
                        'options' => ['placeholder' => 'Выберите '],
                        'pluginOptions' => [
                            'tags' => true,
                            'allowClear' => true,
                        ],
                    ]);
                    ?>

            </div>
            <div class="col-md-6">
                <?=
                $form->field($model, 'phone')->widget(\yii\widgets\MaskedInput::className(), [
                    'mask' => '+7 (999)-999-99-99'
                ]);
                ?>
            </div>
        </div>
    

        <div class="row">
            <div class="col-md-12">
                    <?= $form->field($model, 'request')->textarea(['rows' => 6]) ?>
            </div>
        </div>



        <div class="row">
            <div class="col-md-6">
                    <?= $form->field($model, 'accepted_id')->widget(Select2::class, [
                        'data' => ArrayHelper::map(\app\models\User::find()->all(), 'id', 'name'),
                        'options' => [
                            'placeholder' => 'Выберите',
                            'value' => Yii::$app->user->identity->id,
                        ],
                    ]) ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'fulfilled_id')->widget(Select2::class, [
                    'data' => ArrayHelper::map(\app\models\User::find()->all(), 'id', 'name'),
                    'options' => [
                        'placeholder' => 'Выберите'
                    ],
                ]) ?>
            </div>
        </div>
    

        <div class="row">
            <div class="col-md-12">
                    <?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>
            </div>
        </div>


        <div class="row">
            <div class="col-md-3">
                    <?= $form->field($model, 'payment')->dropDownList([
                            'Безнал' => 'Безнал',
                            'Нал' => 'Нал',
                            'Kaspi' => 'Kaspi'
                    ])?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'material_price')->textInput([
                    'onChange' => $matPrice
                ]) ?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'price_of_work')->textInput([
                    'onChange' => $workPrice
                ]) ?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'sum')->textInput() ?>
            </div>
        </div>
    


	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/applications/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model Applications */

?>
<div class="applications-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/applications/index.php
<?php


use kartik\export\ExportMenu;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel ApplicationsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = "Заявки";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>

<div class="panel panel-inverse project-index">
    <div class="panel-heading">
        <!--        <div class="panel-heading-btn">-->
        <!--        </div>-->
        <h4 class="panel-title">Заявки</h4>
    </div>
    <div class="panel-body">
<div class="applications-index">

    <div class="row">
        <div class="col-md-2">
            <?php $form = ActiveForm::begin(['id' => 'search-form', 'method' => 'GET']); ?>
            <?= $form->field($searchModel, 'search')->textInput()->label(false) ?>

        </div>
        <div class="col-md-3">
            <?= Html::a('Сбросить', ['/applications/index'], ['class' => 'btn btn-default']) ?>
            <?= Html::submitButton('Применить', ['class' => 'btn btn-success']) ?>

            <?php ActiveForm::end() ?>
        </div>
    </div>
    <?php Pjax::begin(['id' => 'pjax-container-info-container', 'enablePushState' => false]); ?>
    <div class="row">
        <?php
        $download =  ExportMenu::widget([
            'dataProvider' => $dataProvider,
            'columns' => require(__DIR__.'/_columns.php'),
            'fontAwesome' => true,
            'dropdownOptions' => [
                'label' => 'Скачать',
                'class' => 'btn btn-success'
            ],
            'showColumnSelector' => false,
            'clearBuffers' => true,
            'exportConfig' => [
                ExportMenu::FORMAT_TEXT => false,
                ExportMenu::FORMAT_HTML => false,
                ExportMenu::FORMAT_EXCEL => false,
                ExportMenu::FORMAT_CSV => false,
                ExportMenu::FORMAT_PDF => false,
            ],
            'showConfirmAlert' => false,
        ]);
        ?>
    </div>
    <div id="ajaxCrudDatatable">

        <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'panelBeforeTemplate' =>    Html::a('Добавить <i class="fa fa-plus"></i>', ['create'],
                ['role'=>'modal-remote','title'=> 'Добавить проект','class'=>'btn btn-success']).'&nbsp;'.
                Html::a('<i class="fa fa-repeat"></i>', [''],
                ['data-pjax'=>1, 'class'=>'btn btn-white', 'title'=>'Обновить']). '<span style="margin-left:10px">'.$download.'</span>' ,
            'striped' => true,
            'condensed' => true,
            'responsive' => true,          
            'panel' => [
                'headingOptions' => ['style' => 'display: none;'],
//                'after'=>BulkButtonWidget::widget([
//                            'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Удалить все',
//                                ["bulk-delete"] ,
//                                [
//                                    "class"=>"btn btn-danger btn-xs",
//                                    'role'=>'modal-remote-bulk',
//                                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
//                                    'data-request-method'=>'post',
//                                    'data-confirm-title'=>'Are you sure?',
//                                    'data-confirm-message'=>'Вы действительно хотите удалить эту запись?'
//                                ]),
//                        ]).
//                        '<div class="clearfix"></div>',
            ]
        ])?>
    </div>
</div>
    </div>
</div>
<?php Pjax::end() ?>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/applications/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model Applications */
?>
<div class="applications-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>